backend:
  name: git-gateway
  branch: main
  local_backend: true

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "properties"
    label: "Properties"
    folder: "content/properties"
    create: true
    slug: "{{fields.slug}}" # <-- use hidden field
    format: "json"

    fields:
      - label: "Slug"
        name: "slug"
        widget: "hidden"
        default: "{{uuid}}"

      - label: "Property Title"
        name: "title"
        widget: "string"
        required: false
        default: ""

      - label: "Price"
        name: "price"
        widget: "string"
        required: false
        default: ""

      - label: "Location"
        name: "location"
        widget: "string"
        required: false
        default: ""

      - label: "Image (Flyer)"
        name: "image"
        widget: "image"
        required: false
        allow_multiple: false

      - label: "Extra Notes"
        name: "body"
        widget: "text"
        required: false
        default: ""